- name: Run docker image clean up
  hosts: "*"
  tasks:
    - name: Start garbage collector container
      package:
        name: "{{ docker }}"
        state: present
      docker_container:
        name: docker-gc
        image: spotify/docker-gc
        state: started
        auto_remove: yes
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc:/etc:ro
