- name: Run docker image clean up
  hosts: "*"
  tasks:
    - name: Check if docker is installed
      shell: dpkg-query -W -f='${Status}' docker | grep 'install ok installed'
      register: is_installed
      failed_when: no
      changed_when: no

    - name: Start garbage collector container
      when: is_installed.rc == 0
      docker_container:
        name: docker-gc
        image: spotify/docker-gc
        state: started
        auto_remove: yes
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc:/etc:ro
