- name: Run docker image clean up
  hosts: "*"
  tasks:
    - name: Check if docker is installed
      package:
        name: "docker"
        state: present
      check_mode: true
      register: package_check

    - name: Start garbage collector container
      docker_container:
        name: docker-gc
        image: spotify/docker-gc
        state: started
        auto_remove: yes
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc:/etc:ro
      when: package_check is succeeded
