- name: Run docker image clean up
  hosts: "*"
  tasks:
    - name: Check if docker is installed
      command: dpkg-query -l docker
      register: deb_check

    - name: Start garbage collector container
      when: deb_check.stdout.find('no packages found') != 1
      docker_container:
        name: docker-gc
        image: spotify/docker-gc
        state: started
        auto_remove: yes
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc:/etc:ro
