- name: Run docker image clean up
  hosts: "*"
  tasks:
    - name: Check current docker version
      command: docker --version
      register: package_check
      changed_when: false
      failed_when: false
      check_mode: no

    - name: Run Docker image prune -f
      become: true
      register: image
      shell: docker image prune -f
      changed_when: "image.stderr != 'Total reclaimed space: 0B'"
      when: package_check.stdout is defined

    - name: Run Docker volume prune -f
      become: true
      shell: docker volume prune -f
      register: volume
      changed_when: "volume.stderr != 'Total reclaimed space: 0B'"
      when: package_check.stdout is defined
